name: Test & Deploy fake-useragent

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', 'pypy-3.8', 'pypy-3.9' ]
    name: Python ${{ matrix.python-version }} Test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install depedencies
        run: pip install -r requirements.txt
      - name: Run tets
        run: tox
