name: Test & Deploy fake-useragent

on: [push, pull_reuqest, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest # [macos-latest, ubuntu-latest, windows-latest]
    strategy:
      # fail-fast: false
      matrix:
        python-version: ["3.x", "pypy-3.8", "pypy-3.9"]
    name: Python ${{ matrix.python-version }} Test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install depedencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: tox
